### PR TITLE
Improve error message when issue data structure is unexpected.

### PR DESCRIPTION
**Pull request by sminnee**
Provides more diagnostics for #54.

### CODE REVIEW

**Comment by sminnee** [comment]
@luandy64 could we merge this and push to StitchData.com?

**Comment by luandy64** [comment]
I don't think this is the right approach for the problem. 

We can use `requests`'s `raise_for_status()` and get the response you are looking for. I encourage you to change `authed_get_all_pages()` in the tap to call `raise_for_status()` just before it `yield`s.

**Comment by luandy64** [comment]
Also just to clarify, have you been running the tap locally and testing things?

**Comment by sminnee** [comment]
I've generally been running the tap locally. However, I am unable to replicate this error situation on my local environment.

I don't think that raise_for_status is what's needed here. I believe that the response is still a 200 response, but it has an unexpected data structure.

**Comment by sminnee** [comment]
Right, yes, I see now that the response created is a 502.

**Comment by sminnee** [comment]
I have amended the PR as recommended.

**Pull request merged**
