### PR TITLE
Support custom domain (gh:e)

### LINKED ISSUE #23: Feature Request: Support domain specification
A Stitch user requested the ability to be able to specify an internal Github endpoint to pull data from, which was not functioning when populating the repository name field of the integration. eg, "github.singer.com" rather than simply `singer-io`, where entering `singer` was non-functional.

They received 401 errors during extraction without much logging surrounding those auth errors, and the extractions eventually ended with schema mismatch (due to no values being returned).

### PR DESCRIPTION
**Pull request by udzura**
# Description of change

Support GitHub Enterprise. This will fix #23 .

# Manual QA steps

 - Add  something like `"api_endpoint": "https://git.your-compony.example.com/api/v3"` to your config json.
 - Run extractor.
 
# Risks

 - Maybe none.
 
# Rollback steps

 - Revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @udzura, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by udzura** [comment]
Singed! I'm waiting for the response.

**Comment by cmerrick** [comment]
You did it @udzura!

Thank you for signing the Singer Contribution License Agreement.

**Comment by BenjMaq** [comment]
This is much needed. Any chance someone could review this please?

**Pull request closed without merging**
