### PR TITLE
Support a string description on an issue label

### PR DESCRIPTION
**Pull request by jcw-**
# Description of change
Fix for https://github.com/singer-io/tap-github/issues/95

# Manual QA steps
 - Set a description on an issue label
 - Apply the label to an issue
 - Observe that validation now succeeds
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by jcw-** [comment]
@jacobrobertbaca minor fix to your recent addition in https://github.com/singer-io/tap-github/pull/92, would you be interested in reviewing?

**Comment by hassankhan** [comment]
Anything we can do to get this PR merged in soon, @KAllan357?

**Comment by luandy64** [comment]
@jcw- @hassankhan I'm working to get #102 merged which includes this change. Follow the status there please

**Comment by jcw-** [comment]
Fixed with #102

**Pull request closed without merging**
